title: Haruki's Meshtastic Experiments
description: >- # this means to ignore newlines until "baseurl:"
  This is a simple ADC calculator.
baseurl: "/Meshtastic-Experiments" # the subpath of your site, e.g. /blog
url: "https://HarukiToreda.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-Hacker
plugins:
  - jekyll-feed
