title: Haruki's Meshtastic Experiments
description: >-
  Just my personal experiments.
baseurl: "/Meshtastic-Experiments" # the subpath of your site, e.g. /blog
url: "https://HarukiToreda.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-feed

# Add navigation links
navbar:
  - title: Battery Runtime Tests
    url: "/Battery-Runtime-Tests"
  - title: ADC Calculator
    url: "/ADC-Calculator"
  - title: LoRa Boards Comparison Table
    url: "/LoRa-Boards-Comparison-Table"
  - title: LoRa Boards Power Measurements
    url: "/LoRa-Boards-Power-Measurements"
  - title: LoRa Boards Comparison2 Table
    url: "/LoRa-Boards-Comparison2-Table"
  - title: Additional Hardware
    url: "/Additional-Hardware"

# Point to the local theme directories
layouts_dir: _theme/_layouts
includes_dir: _theme/_includes
sass:
  sass_dir: _theme/_sass
