title: Haruki's Meshtastic Experiments
description: >-
  This is a simple ADC calculator.
baseurl: "/Meshtastic-Experiments" # the subpath of your site, e.g. /blog
url: "https://HarukiToreda.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-feed

# Add navigation links
navbar:
  - title: Home
    url: "/"
  - title: Battery Runtime Tests
    url: "/Meshtastic-Experiments/Battery-Runtime-Tests"
  - title: ADC Calculator
    url: "/Meshtastic-Experiments/ADC-Calculator"
  - title: LoRa Boards Comparison Table
    url: "/Meshtastic-Experiments/LoRa-Boards-Comparison-Table"
  - title: LoRa Boards Power Measurements
    url: "/Meshtastic-Experiments/LoRa-Boards-Power-Measurements"

title: Haruki's Meshtastic Experiments
description: >-
  This is a simple ADC calculator.
baseurl: "/Meshtastic-Experiments" # the subpath of your site, e.g. /blog
url: "https://HarukiToreda.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-feed

# Point to the local theme directories
layouts_dir: _theme/_layouts
includes_dir: _theme/_includes
sass:
  sass_dir: _theme/_sass

# Add navigation links
navbar:
  - title: Home
    url: "/Meshtastic-Experiments/"
  - title: Battery Runtime Tests
    url: "/Battery Runtime Tests"
  - title: ADC Calculator
    url: "/ADC-Calculator"
  - title: LoRa Boards Comparison Table
    url: "/LoRa Boards Comparison Table"
  - title: LoRa Boards Power Measurements
    url: "/LoRa Boards Power Measurements"
