title: Haruki's Meshtastic Experiments
description: >-
  Just my personal experiments.
baseurl: "/Meshtastic-Experiments" # the subpath of your site, e.g. /blog
url: "https://HarukiToreda.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-feed

# Add navigation links with a dropdown for Release Notes
navbar:
  - title: Battery Runtime Tests
    url: "/Battery-Runtime-Tests"
  - title: LoRa Boards Power Measurements
    url: "/LoRa-Boards-Power-Measurements"
  - title: Antennas Tested
    url: "/Antennas-Tested"
  - title: ADC Calculator
    url: "/ADC-Calculator"
  - title: Shopping Guides
    sublinks:
    - title: LoRa Boards Comparison Table
      url: "/LoRa-Boards-Comparison-Table"
    - title: Recomended Etsy/Tindie Nodes
      url: "/Complete-nodes-List"
  #- title: Release Notes
  #  sublinks:
  #    - title: 2.5.6.d55c08d Alpha
  #      url: "/release-notes/firmware-2-5-6"
  - title: Compatible Peripherals
    url: "/Compatible-Peripherals"
  - title: Contact Me
    url: "/contact"    
 

# Point to the local theme directories
layouts_dir: _theme/_layouts
includes_dir: _theme/_includes
sass:
  sass_dir: _theme/_sass
