name: InkHUD Todo List

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_todo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch latest todo.txt
        run: |
          curl -o todo.txt https://raw.githubusercontent.com/todd-herbert/meshtastic-firmware/InkHUD/todo.txt

      - name: Format into Markdown
        run: |
          echo "---" > Todo-List.md
          echo "layout: default" >> Todo-List.md
          echo "title: Todo List" >> Todo-List.md
          echo "---" >> Todo-List.md
          echo "# Todo List" >> Todo-List.md
          echo "" >> Todo-List.md
          echo "**Last updated: $(date -u)**" >> Todo-List.md
          echo "" >> Todo-List.md
          echo "## Features" >> Todo-List.md
          awk '/Features/{flag=1;next}/^$/{flag=0}flag' todo.txt | sed -E 's/\[\]/- [ ]/g; s/\[wip\]/- 🛠 **(WIP)**/g' >> Todo-List.md
          echo "" >> Todo-List.md
          echo "## Critical Tasks" >> Todo-List.md
          awk '/Critical Tasks/{flag=1;next}/^$/{flag=0}flag' todo.txt | sed -E 's/\[\]/- [ ]/g; s/\[wip\]/- 🛠 **(WIP)**/g' >> Todo-List.md
          echo "" >> Todo-List.md
          echo "## Improvements" >> Todo-List.md
          awk '/Improvements/{flag=1;next}/^$/{flag=0}flag' todo.txt | sed -E 's/\[\]/- [ ]/g; s/\[wip\]/- 🛠 **(WIP)**/g' >> Todo-List.md
          echo "" >> Todo-List.md
          echo "## Known Bugs" >> Todo-List.md
          awk '/Known Bugs/{flag=1;next}/^$/{flag=0}flag' todo.txt | sed -E 's/\[\]/- [ ]/g; s/\[wip\]/- 🛠 **(WIP)**/g' >> Todo-List.md
          echo "" >> Todo-List.md
          echo "## Chores" >> Todo-List.md
          awk '/Chores/{flag=1;next}/^$/{flag=0}flag' todo.txt | sed -E 's/\[\]/- [ ]/g; s/\[wip\]/- 🛠 **(WIP)**/g' >> Todo-List.md
          echo "" >> Todo-List.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Todo-List.md
          git commit -m "Automated update of Todo List" || echo "No changes to commit"
          git push origin main
