name: InkHUD Todo List

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_todo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch latest todo.txt
        run: |
          curl -o todo.txt https://raw.githubusercontent.com/todd-herbert/meshtastic-firmware/InkHUD/todo.txt

      - name: Ensure Directories Exist
        run: |
          mkdir -p InkHUD

      - name: Extract Previous Completed Section
        run: |
          if [ -f "InkHUD/Todo-List.md" ]; then
            awk '/## Completed/{flag=1; next} flag' InkHUD/Todo-List.md > completed.txt
          else
            touch completed.txt
          fi

      - name: Create Updated Todo List
        run: |
          echo "---" > InkHUD/Todo-List.md
          echo "layout: default" >> InkHUD/Todo-List.md
          echo "title: Todo List" >> InkHUD/Todo-List.md
          echo "---" >> InkHUD/Todo-List.md
          echo "# Todo List" >> InkHUD/Todo-List.md
          echo "" >> InkHUD/Todo-List.md
          echo "**Last updated: $(date -u)**" >> InkHUD/Todo-List.md
          echo "" >> InkHUD/Todo-List.md
          echo "## Features" >> InkHUD/Todo-List.md
          awk '/Features/{flag=1;next}/^$/{flag=0}flag' todo.txt | sed -E 's/\[\]/- [ ]/g; s/\[wip\]/- 🛠 **(WIP)**/g' >> InkHUD/Todo-List.md
          echo "" >> InkHUD/Todo-List.md
          echo "## Critical Tasks" >> InkHUD/Todo-List.md
          awk '/Critical Tasks/{flag=1;next}/^$/{flag=0}flag' todo.txt | sed -E 's/\[\]/- [ ]/g; s/\[wip\]/- 🛠 **(WIP)**/g' >> InkHUD/Todo-List.md
          echo "" >> InkHUD/Todo-List.md
          echo "## Improvements" >> InkHUD/Todo-List.md
          awk '/Improvements/{flag=1;next}/^$/{flag=0}flag' todo.txt | sed -E 's/\[\]/- [ ]/g; s/\[wip\]/- 🛠 **(WIP)**/g' >> InkHUD/Todo-List.md
          echo "" >> InkHUD/Todo-List.md
          echo "## Known Bugs" >> InkHUD/Todo-List.md
          awk '/Known Bugs/{flag=1;next}/^$/{flag=0}flag' todo.txt | sed -E 's/\[\]/- [ ]/g; s/\[wip\]/- 🛠 **(WIP)**/g' >> InkHUD/Todo-List.md
          echo "" >> InkHUD/Todo-List.md
          echo "## Chores" >> InkHUD/Todo-List.md
          awk '/Chores/{flag=1;next}/^$/{flag=0}flag' todo.txt | sed -E 's/\[\]/- [ ]/g; s/\[wip\]/- 🛠 **(WIP)**/g' >> InkHUD/Todo-List.md
          echo "" >> InkHUD/Todo-List.md

      - name: Identify Removed Tasks & Append to Completed
        run: |
          # Extract current tasks
          grep -E "^- \[ \]" InkHUD/Todo-List.md |
